version: '3.4'

services:
    demanddb:
        image: mongo

    demands.api:
        image: ${DOCKER_REGISTRY-}demandsapi
        build:
            context: .
            dockerfile: src/Demand/Demand/Dockerfile

    customerdb:
        image: mongo

    customer.api:
        image: ${DOCKER_REGISTRY-}customerapi
        build:
            context: .
            dockerfile: src/Customer/Customer.API/Dockerfile

    companydb:
        image: mongo

    company.api:
        image: ${DOCKER_REGISTRY-}companyapi
        build:
            context: .
            dockerfile: src/Company/Company.API/Dockerfile

