version: '3.4'

services:

    demanddb:
        container_name: demanddb
        restart: always
        volumes: 
            - ~/mongo/data:/data/catalogdb
        ports:
            - "27001:27017"

    demands.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "DemandDatabaseSettings:ConnectionString=mongodb://demanddb:27017"
        ports:
            - "8000:80"
        volumes:
            - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

        depends_on:
            - "demanddb"