version: '3.4'

services:

    rabbitmq:
        container_name: rabbitmq
        restart: always
        hostname: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"

    demanddb:
        container_name: demanddb
        volumes: 
            - demanddbdata:/data/db
        ports:
            - "5001:27017"

    demands.api:
        container_name: demandsapi 
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "DemandDatabaseSettings:ConnectionString=mongodb://demanddb:27017"
        ports:
            - "8001:80"
        volumes:
            - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

        depends_on:
            - "demanddb"
            - "rabbitmq"
        restart: on-failure


    customerdb:
        container_name: customerdb
        volumes: 
            - customerdbdata:/data/db
        ports:
            - "5002:27017"

    customer.api:
        container_name: customerapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "CustomerDatabaseSettings:ConnectionString=mongodb://customerdb:27017"
        ports:
            - "8002:80"
        volumes:
            - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
        depends_on:
            - "customerdb"
            - "rabbitmq"
        restart: on-failure

    companydb:
        container_name: companydb
        volumes: 
            - companydbdata:/data/db
        ports:
            - "5003:27017"

    company.api:
        container_name: companyapi 
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "CompanyDatabaseSettings:ConnectionString=mongodb://companydb:27017"
        ports:
            - "8003:80"
        volumes:
            - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
        depends_on:
            - "companydb"
            - "rabbitmq"
        restart: on-failure


    vehicledb:
        container_name: vehicledb
        volumes: 
            - vehicledbdata:/data/db
        ports:
            - "5005:27017"

    vehicle.api:
        container_name: vehicleapi 
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "VehicleDatabaseSettings:ConnectionString=mongodb://vehicledb:27017"
        ports:
            - "8005:80"
        volumes:
            - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
        depends_on:
            - "vehicledb"
            - "rabbitmq"
        restart: on-failure

    offerdb:
        container_name: offerdb
        volumes: 
            - offerdbdata:/data/db
        ports:
            - "5008:27017"

    offer.api:
        container_name: offerapi 
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "OfferDatabaseSettings:ConnectionString=mongodb://offerdb:27017"
        ports:
            - "8008:80"
        volumes:
            - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
        depends_on:
            - "offerdb"
            - "rabbitmq"
        restart: on-failure