version: '3.4'

services:
    demanddb:
        image: mongo

    demands.api:
        image: ${DOCKER_REGISTRY-}demandsapi
        build:
            context: .
            dockerfile: src/Demand/Demand/Dockerfile

    customerdb:
        image: mongo

    customer.api:
        image: ${DOCKER_REGISTRY-}customerapi
        build:
            context: .
            dockerfile: src/Customer/Customer.API/Dockerfile

    companydb:
        image: mongo

    company.api:
        image: ${DOCKER_REGISTRY-}companyapi
        build:
            context: .
            dockerfile: src/Company/Company.API/Dockerfile

    vehicledb:
        image: mongo

    vehicle.api:
        image: ${DOCKER_REGISTRY-}vehicleapi
        build:
            context: .
            dockerfile: src/Vehicle/Vehicle.API/Dockerfile

    client:
        build: 
            context: ./src/client/client-app
            dockerfile: Dockerfile
        container_name: client
        restart: on-failure
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        volumes:        
            - ./src/client/client-app/src:/client-app/src
            - '/client-app/node_modules'